### ISSUE TITLE
Add &version=3 to the video URLs

### ISSUE THREAD

**Issue by ryanschneider** [AnuragMishra/YoutubePlayer#2]
I don't have a pull request for this, but FWIW we just ran into some issues with the script because it didn't have &version=3 on the youtube.com URLs, e.g.:

var videoUrl = 'http://www.youtube.com/v/{videoId}?enablejsapi=1&version=3&playerapiid={playerId}';

Not sure if they are only needed for our customized version or not, as your jsFiddle still worked fine.

Thanks,
Ryan

**Comment by AnuragMishra** [comment]
Ryan,

I don't know what the API may be doing in the absence of the version parameter, but the API examples were using it awfully lot in their examples. Also, this seems to be the latest version, so I've added it to the base URL that in the script.

Thanks for bringing this up.

Anurag
